version: "3.3"
services:
  backend:
    build: .
    image: generate-check:latest
    container_name: generate_check
    env_file:
      - ./.env.postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: generate_check_db
    ports:
      - "54320:5432"
    env_file:
      - ./.env.postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_CHECK:-generate_check_db}